# Generated by Django 4.2.3 on 2023-07-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default='1', verbose_name='Estatus'),
        ),
    ]
