# Generated by Django 4.2.3 on 2023-08-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls', '0004_alter_url_componente_alter_url_servidor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Interna'), (2, 'Externa'), (3, 'PI-PO'), (4, 'DataPower')], default='1', verbose_name='Tipo'),
        ),
    ]
