# Generated by Django 4.2.3 on 2023-07-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('fechaCompromiso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Compromiso')),
                ('estatus', models.IntegerField(blank=True, null=True, verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
            ],
            options={
                'verbose_name': 'Smax',
                'verbose_name_plural': 'Smaxs',
                'ordering': ['numero'],
            },
        ),
    ]
