# Generated by Django 4.2.2 on 2023-07-24 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('fechaCompromiso', models.DateField(blank=True, null=True, verbose_name='Fecha Compromiso')),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default='1', verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Smax',
                'verbose_name_plural': 'Smaxs',
                'ordering': ['numero'],
            },
        ),
    ]
