# Generated by Django 4.2.3 on 2023-08-05 22:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smaxs', '0003_smax_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smax',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
