# Generated by Django 4.2.3 on 2023-08-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smaxs', '0004_alter_smax_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='smax',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=80, null=True, verbose_name='nombre'),
        ),
    ]
