# Generated by Django 4.2.3 on 2023-07-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '__first__'),
        ('sistemas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCorto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre Corto')),
                ('nombreLargo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre Largo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Version')),
                ('lenguaje', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lenguaje')),
                ('tipo', models.IntegerField(blank=True, null=True, verbose_name='Tipo')),
                ('estatus', models.IntegerField(blank=True, null=True, verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['nombreCorto', 'version'],
            },
        ),
    ]
