# Generated by Django 4.2.3 on 2023-08-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('componentes', '0003_alter_componente_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componente',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Programa'), (2, 'Web Services'), (3, 'Api'), (4, 'Scipt'), (5, 'FA')], default='1', verbose_name='Tipo'),
        ),
    ]
