# Generated by Django 4.2.2 on 2023-07-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('componentes', '__first__'),
        ('smaxs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numero')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('tipo', models.IntegerField(blank=True, null=True, verbose_name='tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('fechaInscripcion', models.DateField(blank=True, null=True, verbose_name='Fecha de Inscripcion')),
                ('fechaCambio', models.DateField(blank=True, null=True, verbose_name='Fecha del Cambio')),
                ('aplico', models.CharField(blank=True, max_length=150, null=True, verbose_name='Quin Aplico')),
                ('resultado', models.IntegerField(blank=True, null=True, verbose_name='Resultado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='componentes.componente')),
                ('smax', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smaxs.smax')),
            ],
            options={
                'verbose_name': 'Cambio',
                'verbose_name_plural': 'Cambios',
                'ordering': ['numero', 'nombre'],
            },
        ),
    ]
