# Generated by Django 4.2.3 on 2023-07-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio',
            name='resultado',
            field=models.IntegerField(choices=[(1, 'Inscrito'), (2, 'Aprobado'), (3, 'Cerrado'), (4, 'Cancelado'), (5, 'Rechazado')], default='1', verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='cambio',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Menor'), (2, 'Mayo'), (3, 'Urgente'), (4, 'Standar')], default='1', verbose_name='Tipo'),
        ),
    ]
