# Generated by Django 4.2.3 on 2023-07-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smaxs', '0001_initial'),
        ('componentes', '0001_initial'),
        ('cambios', '0002_alter_cambio_resultado_alter_cambio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio',
            name='componente',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='componentes.componente'),
        ),
        migrations.AlterField(
            model_name='cambio',
            name='smax',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='smaxs.smax'),
        ),
    ]
