# Generated by Django 4.2.3 on 2023-08-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cambios', '0004_alter_cambio_descripcion_alter_cambio_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambio',
            name='aplico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Quien Aplico'),
        ),
    ]
