# Generated by Django 4.2.2 on 2023-07-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagrama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='Path')),
                ('tipo', models.IntegerField(choices=[(1, 'Diagrama'), (2, 'Descripcion'), (3, 'Metodologia')], default='1', verbose_name='Tipo')),
                ('estatus', models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default='1', verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.sistema')),
            ],
            options={
                'verbose_name': 'Diagrama',
                'verbose_name_plural': 'Diagramas',
                'ordering': ['nombre'],
            },
        ),
    ]
