# Generated by Django 4.2.3 on 2023-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagrama',
            name='tipo',
            field=models.IntegerField(choices=[('1', 'Diagrama'), ('2', 'Descripcion'), ('3', 'Metodologia')], default='1', verbose_name='Tipo'),
        ),
    ]
