# Generated by Django 4.2.3 on 2023-08-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0003_alter_diagrama_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagrama',
            name='path',
        ),
        migrations.AddField(
            model_name='diagrama',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='diagramas/'),
        ),
    ]
