# Generated by Django 4.2.3 on 2023-07-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagramas', '0003_alter_diagrama_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagrama',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Inactivo')], default='1', verbose_name='Estatus'),
        ),
    ]
