# Generated by Django 4.2.3 on 2023-07-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='siglas',
            field=models.CharField(blank=True, default='SS', max_length=15, null=True, verbose_name='Siglas'),
        ),
    ]
