# Generated by Django 4.2.3 on 2023-07-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsables', '0001_initial'),
        ('sistemas', '0002_sistema_siglas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='responsable',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='responsables.responsable'),
        ),
    ]
