# Generated by Django 4.2.3 on 2023-08-05 21:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0003_alter_sistema_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='descripcion',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
    ]
