# Generated by Django 4.2.3 on 2023-08-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0004_alter_sistema_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='siglas',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Siglas'),
        ),
    ]
