# Generated by Django 4.2.2 on 2023-07-24 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servidores', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nombre')),
                ('manejador', models.CharField(blank=True, max_length=50, null=True, verbose_name='Manejador')),
                ('usuario', models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario')),
                ('password', models.CharField(blank=True, max_length=30, null=True, verbose_name='Password')),
                ('puerto', models.CharField(blank=True, max_length=6, null=True, verbose_name='Puerto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modificado')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servidores.servidor')),
            ],
            options={
                'verbose_name': 'Database',
                'verbose_name_plural': 'Databases',
                'ordering': ['nombre'],
            },
        ),
    ]
